---
name: build

on:

  push:
    branches:
      - main
      - release/*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: ./scripts/build.sh clean
      - run: ./scripts/build.sh prepare
      - run: ./scripts/build.sh compile
