---
name: pull requests

on:

  pull_request:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: ./scripts/build.sh clean
      - run: ./scripts/build.sh prepare
      - run: ./scripts/build.sh compile
