---
name: pull requests

on:

  pull_request:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/build.sh clean
      - run: ./scripts/build.sh prepare
      - run: ./scripts/build.sh compile

      - uses: anchore/sbom-action/download-syft@v0.15.0

      - run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin

      # Increment version and tag.
      - run: autotag --scheme=conventional
