---
# https://pkg.go.dev/github.com/pantheon-systems/autotag#section-readme
name: release

on:

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  # Need to write releases.
  contents: write
  # Need for ghcr access.
  packages: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: ./scripts/build.sh clean
      - run: ./scripts/build.sh prepare
      - run: ./scripts/build.sh compile

      - uses: anchore/sbom-action/download-syft@v0.15.0

      - run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin

      # Login to ghcr.
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Increment version and tag.
      - run: |
          # https://github.com/pantheon-systems/autotag#troubleshooting
          git fetch --tags --unshallow --prune

          if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then
            # Ensure a local 'main' branch exists at 'refs/heads/main'.
            git branch --track main origin/main
          fi

          autotag -v --scheme=conventional

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag:
          files: |
            LICENSE
            target/*.pdf
