---
# https://pkg.go.dev/github.com/pantheon-systems/autotag#section-readme
name: release

on:

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  # Need to write releases.
  contents: write
  # Need for ghcr access.
  packages: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Clean
        run: ./scripts/build.sh clean
      - name: Prepare
        run: ./scripts/build.sh prepare
      - name: Compile
        run: ./scripts/build.sh compile

      - uses: anchore/sbom-action/download-syft@v0.17.6

      - name: Install autotag
        run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin

      # Login to ghcr.
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version and tag
        id: tag
        run: |
          # https://github.com/pantheon-systems/autotag#troubleshooting
          git fetch --tags --unshallow --prune

          if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then
            # Ensure a local 'main' branch exists at 'refs/heads/main'.
            git branch --track main origin/main
          fi

          autotag -v --scheme=conventional

          git push --tags origin main

          echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Rename artifacts
        run: ./scripts/rename-artifacts.sh
        env:
          VERSION: "${{ steps.tag.outputs.version }}"

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "${{ steps.tag.outputs.version }}"
          files: |
            LICENSE
            target/artifacts/*.pdf
